apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: opi2kwl7f-nodejs-gitops
  description: This is GitOps manifest for opi2kwl7f-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=opi2kwl7f-nodejs
    backstage.io/kubernetes-id: opi2kwl7f-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: opi2kwl7f-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:opi2kwl7f-nodejs
