apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: opi2kwl7f-nodejs
  janus-idp.io/tekton: opi2kwl7f-nodejs
  backstage.io/kubernetes-id: opi2kwl7f-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: opi2kwl7f-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
